@url = http://127.0.0.1:3000
@json = Content-Type: application/json

### 登录
POST {{url}}/admin/login
{{json}}

{
    "username": "SuperficialL",
    "password": "123456"
}


### 注册
POST {{url}}/admin/register
{{json}}

{
    "username": " test 1",
    "password": "123456",
    "password2": "123456",
    "email": "347106739@qq.com"
}

### 请求当前用户信息
### params:{token}
GET {{url}}/admin/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNmJhNTVkN2FiYWQyNDNlM2E0OGJjZCIsImlhdCI6MTU2NzkxNjUxOCwiZXhwIjoxNTY3OTIwMTE4fQ.9pCH227jRcesgzphtOXNfUTm4Z1ub6yPqm2qHtKvQ08

### 查询所有分类
### params:{}
GET {{url}}/admin/categories


### 通过{id}查询分类详情
### params:{id:objectId}
GET {{url}}/admin/categories/5d19af690f0d7233e453c590


### 创建分类 
### params: {name:string,parent:objectId}
POST {{url}}/admin/categories
{{json}}

{
    "name": "测试"
}


### 删除分类
### params: {id:objectId}
DELETE {{url}}/admin/categories/5d667873afbe7026d059f634


### 修改分类
### params: {id:objectId,data:{name:string,parent:objectId}}
PUT {{url}}/admin/categories/5d667873afbe7026d059f634
{{json}}

{
    "name": "test"
}


### 查询文章详情
### params:{id:objectId}
GET {{url}}/admin/articles/5d1ed4623f090430981449f9
